### ISSUE TITLE
Bug after restart

### ISSUE THREAD

**Issue by BliXem1** [jonasbkarlsson/ev_smart_charging#102]
Hi,

I'm running your latest version 1.5.1, but every time I restarted this happens:

Logger: homeassistant.config_entries
Source: config_entries.py:424
First occurred: 13:35:59 (2 occurrences)
Last logged: 13:36:03

Config entry 'EV Smart Charging' for ev_smart_charging integration not ready yet: Input sensors not ready.; Retrying in background

It will work after that, but I'm losing my configuration, I need to adjust the charging speed and the elec. price everytime.

**Comment by jonasbkarlsson** [comment]
The `Input sensors not ready.; Retrying in background` is normal. The integration waits for all input sensors to be ready before starting.

As of v1.5.0 it is possible to change some of the configuration parameters using configuration entities. However, it is still possible to change the configuration parameters in `Settings -> Devices & Services -> Integrations`. In the current version of the implementation, after restart, the confirguration parameters are set to the values set in  `Settings -> Devices & Services -> Integrations`. And not to the latest value set by the configuration entities. 

It sounds like this is what you see. You have changed some of the configuration paramters using the configuration entities, and after reset the values have been reset back to the original values.

I agree that this is not the preferred behaviour. I already have in my plans to fix this.

**Comment by BliXem1** [comment]
Alright, thanks for your quick reply! I changed the orginal values via Settings -> Devices & Services -> Integrations

**Comment by jonasbkarlsson** [comment]
Have looked into this a bit, and it seems like there is no simple way to restore the configuration settings after restart if both ways of changing the configuration parameteres are used. Or is there?

The best solution I have now is to remove `Settings -> Devices & Services -> Integrations -> EV Smart Charging -> CONFIGURE`, and only use `Settings -> Devices & Services -> Integrations -> EV Smart Charging -> 1 device -> Configuration`.

**Comment by BliXem1** [comment]
For me it's fixed when I changed the orginal values via settings -> devices & services -> integrations -> EV Smart charging ->  configuration :)

**Comment by jonasbkarlsson** [comment]
Yes, I know you know how to avoid this issue. But others might have the same problem, and for them your solution might not be the preferred one. One specific case if you want to be able to modified one of the configuration parameters with a card on the dashboard, then you really would like the value set by the configuration entity to be persistant over restarts.

**Comment by jonasbkarlsson** [comment]
Fixed by release [v1.6.0](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.6.0).
