### ISSUE TITLE
Conditional continuous charging session

### ISSUE THREAD

**Issue by Strixx76** [jonasbkarlsson/ev_smart_charging#103]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to be able set a minimum saved amount of money when switching to non-continuous charging.

**Describe alternatives you've considered**
None

**Additional context**
When ever a schedule is calculated and `switch.ev_smart_charging_continuous_charging_preferred` is off, the integration should do two schedules. One with continuous charging and one where the charging is split into different session, and then compare the amount of money saved by not use a continuous charging. This can be either the total amount (a bit harder) or the difference in average price for the selected hours. And only if the save is greater than the set minimum save, it should do non-continuous charging.
If you go for the total amount saved suggestion, there will be another nice feature for free. That is that there can be a sensor with the estimated total cost for the next planned charging period.

My thought is that there is no meaning in postponing the the final charging if there is not so much to save. As it is now there can be a gap in the charging and you only saves one or two cents in total. Then there is a question if you really did save those cents, because there is a small cost to start and stop the charging depending on battery temperatures. How much, though, is not known to me...

**Comment by jonasbkarlsson** [comment]
As you say, there is an extra cost to for each start and stop depending on the temperature. And without knowing what that cost is, I feel sceptical about implementing what you suggest. Instead, I would suggest something more simple. For example an automation that turns on and off `switch.ev_smart_charging_continuous_charging_preferred` depending on the outside temperature (assuming the car is parked outside). Turn on when it's cold, turn off when it's warm.

**Comment by Strixx76** [comment]
That is one valid approach. I think I have to do some more investigation in this...

**Comment by jonasbkarlsson** [comment]
I close this for the time being.
