### ISSUE TITLE
More versatile "Keep charger on" option

### ISSUE THREAD

**Issue by Strixx76** [jonasbkarlsson/ev_smart_charging#104]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Possibility to use the keep charger on function but only if SOC is above xx%, and the possibility to still use price limit.

**Describe alternatives you've considered**
None

**Additional context**
As discussed in #99, the last percent takes much longer time to charge and I would like to be able to get this last percents when it doesn't costs to much. By being able to switch on the `switch.ev_smart_charging_keep_charger_on` but with the condition that it should only be left on if SOC is greater than for example 98% and with the price limit applied as well, I would get this functionallity.

**Comment by jonasbkarlsson** [comment]
Not sure I understand what you want to achieve. Is it to reach e.g. 98% as default, and then only reach 100% when the price is low?

Basically you don't want to use the price limit to charge up to 98%, and then use the price limit to charge the last part? If so, then you could set `Minimum EV SOC` to 98% and `switch.ev_smart_charging_apply_price_limit` = ON.

**Comment by Strixx76** [comment]
Ah. I had forgotten how the changes in version 1.5 makes this request sort of impossible.

It happens time from time due to different reasons that I don't reach 100% during scheduled charging session when target is set to 100%. It can be the power watch on the wall box or that the price limit prevents loading. And at that times I would only continue charging if the next hour is below the price limit, except if I have reached about 98% then it would be OK to continue even if the price is above the price limit.

But I think I ALMOST can achieve this with an automation that controls the price limit switch. If I switch off the price limit switch at the very end off a session if the SOC is above 97% that would probably result in a new session scheduled after the first has ended. It would be a one hour session without price limit. BUT it would not be leaving the charger on. It would stop the session and then start it again for one hour, but that would be the next cheapest hour which might not be that hour.

**Comment by jonasbkarlsson** [comment]
If I understand you correctly, then I think that an automation that turns on and off the price limit switch at around 97-98% should achieve what you want.

**Comment by Strixx76** [comment]
No. That will will create the following schedule:
![mock](https://user-images.githubusercontent.com/17635047/212658977-5116e72b-e202-4a5c-b8fd-fe5190d35e74.png)

I wish for the following if SOC reaches for example 98% before the first session ends:
![mock2](https://user-images.githubusercontent.com/17635047/212660508-de8c6c15-0f10-43f1-86f6-5fb044b1c1a1.png)

And if it not (for whatever reason) reaches the 98% I want this:
![mock3](https://user-images.githubusercontent.com/17635047/212660531-d3cf0d52-0270-491f-bb2c-d9d26152ba91.png)

_(Where red back ground indicates that the charger is on)_

But maybe I can use an automation that:
turns on `switch.ev_smart_charging_keep_charger_on`, and
turns off `switch.ev_smart_charging_apply_price_limit`, but only
if SOC is above XX%

But then then question is; will the scheduled session be rescheduled before the session ends? Other wise I am back at the first scenario where the integration will fins the next cheapest hour.

**Comment by jonasbkarlsson** [comment]
I think that might work. So then you need to have one automation that:
- IF `sensor.ev_smart_charging_charging` is `on` AND `SOC is above XX%` THEN turn on `switch.ev_smart_charging_keep_charger_on`

You don't need to turn off `switch.ev_smart_charging_apply_price_limit`. It will turn off automatically when keep charger on is activacted, since they can't be on at the same time.

And then it would probably be good to have another automatation that turns on `switch.ev_smart_charging_apply_price_limit` again later, for example when the charger cable is disconnected from the car, or when it is re-connected for the next charging. And that will then automatically turn off `switch.ev_smart_charging_keep_charger_on`.

**Comment by jonasbkarlsson** [comment]
I close this for the time being.
