### ISSUE TITLE
FR - Implement price sensor Energi Data Service

### ISSUE THREAD

**Issue by woopstar** [jonasbkarlsson/ev_smart_charging#105]
Currently, the integration only supports the Nordpool price integration. Still, there is a growing popularity towards the [Energi Data Service](https://github.com/MTrab/energidataservice) price integration in Denmark, which a lot of people nowadays use for calculating their power prices, including transmission, etc.

It would benefit if the integration is altered, so it also works with the EDS.

The current issue with making that work is that the format of the raw_today prices differs between the two integrations.

Current `raw_today` format in Nordpool:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/2997782/213445915-b9a1994d-9fd0-41c8-9987-c60d589f3dbc.png">

Current `raw_today` format in EDS:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/2997782/213446008-070c338a-4ea3-4179-abf5-5a283f7f9c04.png">

**Comment by jonasbkarlsson** [comment]
Yes, this is planned to be added. Duplicate of feature request #87.

**Comment by woopstar** [comment]
Did not see. Closing this in favor of #87
