### ISSUE TITLE
EV target SOC	not updated 

### ISSUE THREAD

**Issue by hi-computers** [jonasbkarlsson/ev_smart_charging#117]
v1.5.2

## Describe the bug
The EV target SOC (attibute of EV Smart Charging Charging) is not updated when i change the number.ev_smart_charging_minimum_ev_soc

**Comment by jonasbkarlsson** [comment]
The `EV target SOC` and the `number.ev_smart_charging_minimum_ev_soc` are not the same.

The `EV target SOC` is the highest SOC level that charging ever should reach.

The `number.ev_smart_charging_minimum_ev_soc` is used in combination with `switch.ev_smart_charging_apply_price_limit` to make sure that a certain minimum SOC level is reached even if the prices are high.
