### ISSUE TITLE
What's the correct way to start a manual charge?

### ISSUE THREAD

**Issue by mortenmoulder** [jonasbkarlsson/ev_smart_charging#125]
## Version of the custom_component
Version: latest

## Configuration
Tesla Model 3 + Easee Home charger. Car set to charge to 100%, Smart charging is enabled, and it should be done at 7 AM.

So last night I wanted to be 100% sure that I had a 100% charge when I woke up. I've been using the integration for 2-3 days now, and with great success, but I always have that "what if it doesn't charge" in the back of my head. I am using your card example:

![image](https://user-images.githubusercontent.com/1304665/217479111-c4e86278-eb63-4125-8280-69cd6969fe3c.png)

However, as you might be able to see, I have added my Easee Home charger at the bottom as a switch. And surely enough, when I enable the switch, the car starts charging manually.

HOWEVER, and this is probably entirely my fault, charging stopped randomly at 03:44 tonight, but I don't know why. 

![image](https://user-images.githubusercontent.com/1304665/217480569-811cf020-141e-4c99-a1b1-e217ce0e3c28.png)

As you can see, the integration reported that charging was set to true between 3 AM and 7 AM, however, I started charging at 02:03 AM, by enabling the charger. I did NOT press the "Manual start" button. Is this the problem?

Also, take a look at this. I did turn on the charger at 02:03, but nothing turned it off until 05:00 (and then on again 1 second later). So the charger never turned off around 03:44, yet it stopped charging the car at about 85% SoC:

![image](https://user-images.githubusercontent.com/1304665/217481500-91334e34-5b20-47b8-8703-7af7e73e9a5c.png)

Let me know if you want more data.

**Comment by jonasbkarlsson** [comment]
To start with, it's not recommended to use the switch in the Easee integration to control the charger. Instead the recommended way is [described here](https://github.com/jonasbkarlsson/ev_smart_charging#integrating-with-chargers).

That you turned on the charger at 02:03 shouldn't be a problem.

That the charging control from the integration turned off the switch at 05:00 was most likely because the initial charging schedule was 03:00-05:00.

However, since the charger stopped charging at 03:44, the target SOC was not reached at 05:00, and the integration made a new charging schedule 05:00-07:00, and sent a turn on command to the switch at 05:00:01.

This quickly turning off and then on again is a known bug that will be fixed #124.

However, in your case the problem seems to be that the charger stopped at 03:44. But from the information you have provided, there is nothing that indicated that the charger was stopped by the integration.

Do you know why the charging was stopped at 03:44?

As for your question in the title of the issue, to press the "Manually start charging"-button would be good way to manually start charging. Note that this will not deactivate the smart charging. If there is a scheduled charging 03:00-05:00, and you manually start at 02:03, then the integration will stop the charging at 05:00.

**Comment by mortenmoulder** [comment]
Thanks for the reply @jonasbkarlsson 

What is the difference between switch.charger and setting the current on all 3 phases to something? If the current is always set to 16A on 3 phases, and I turn on the charger, it will start charging at 16A on 3 phases. Why set it to 16 (and 0) with `easee.set_circuit_dynamic_limit` when I have the switch available to me?

>Do you know why the charging was stopped at 03:44?

No, unfortunately I do not. I just started a charge about an hour ago at 18%, by pressing the "Manually start charging" button (instead of enabling the charger with the switch), and now I have 3.5 hours to check the state. Still not sure why it stopped at 03:44 out of the blue. All my data checks out. I wish the Easee charger would show how each charge was started and stopped, so we can debug it easier.

**Comment by jonasbkarlsson** [comment]
As I have understood it, using the switch will change some configuraton memory in the charger. This memory is not meant to be changed often. So the lifetime of the charger could become shorter if one does this too often. (I have no idea what too often would be.) The developers of the Easee integration recommends to use `easee.set_circuit_dynamic_limit` instead.

**Comment by mortenmoulder** [comment]
Aha, I see. I will go change that, then.

Can I tell your integration not to use that switch anymore? Or do I have to delete it and add it again?

**Comment by jonasbkarlsson** [comment]
Unfortunetely not. You would need to delete it and add it again. But Home Assistant will assign the same name for the new instance, so you would only need to redo the inital configuration, and then set the configuration entities to what you had before, and then everything should work again.

**Comment by mortenmoulder** [comment]
Sounds good - will try it out and report back!

**Comment by mortenmoulder** [comment]
So it's not really working for me. I can't really get the buttons to function correctly. Calling the service isn't quite working either. Charger is enabled.

No matter what I did to the buttons, or called the service, the car would not charge. I had to manually go into the Easee app and start the charge, which I did at around 11:10 PM. I also enabled the manual charging using the button from your example, which calls the automation that sets all 3 phases to 16A.

However, at 00:00 (cheapest time and 8 minutes ago), the charging suddenly stopped and now it won't resume again automatically. I suspect it's because of the issue #124 you mentioned, because I can see in the log, that it changed from off to on in a second.

![image](https://user-images.githubusercontent.com/1304665/218219182-31c35ff5-2e01-454b-b0cb-1494ea0e8204.png)

The car is NOT charging in this state.

Also, when I plug the car in, it starts charging automatically no matter what hour of the day. Do I need a 4th automation that tells it to stop charging? Because at that point, it doesn't seem very smart anymore.

Let me know what you think.

**Comment by jonasbkarlsson** [comment]
First, just to make sure, you need to remove any schedules that you might have programmed in the Easee charger.

And then you need to have the two automations that changes the max current for the three phases.

And then you need to verify that it works.

1. Connect the car to the Easee charger (at a time the car is less charged than the target SOC)
2. Press "Manually start charging"
3. Check that the car now is be charged.
4. Press "Manually stop charging"
5. Check that the charging is stopped.
6. Press "Manually start charging"
7. Check that the car now is be charged.

If this didn't work, there is likely some errors in the two automations. It is working for others. Don't give up!

**Comment by mortenmoulder** [comment]
It's really, really not consistent :( Yesterday night and today it worked fine. Maybe I just need to keep my hands off the manual buttons, because they've caused a lot of issues for me.

**Comment by mortenmoulder** [comment]
So it has been running automatically for a while now, and I think it's safe to say that it works, as long as I don't manually start the charge 😆 If it comes to that, I will keep an eye out. Thanks!

On a quick note: Do you happen to have a card handy, that can display stuff like "charge starting in x hours" based on the attributes? I could make it myself, but I'd rather ask around first.

**Comment by jonasbkarlsson** [comment]
Good to hear that it works! There are some examples on how to show attributes here #38
