### ISSUE TITLE
Open up for other providers (e.g., Tibber)

### ISSUE THREAD

**Issue by HWiese1980** [jonasbkarlsson/ev_smart_charging#135]
**Is your feature request related to a problem? Please describe.**
Sort of. Tibber for example offers a list of future prices for the next day by means of a GraphQL API. As far as I understand, this information could be used for this integration too to control charging of an EV. 

**Describe the solution you'd like**
I propose a way to integrate arbitrary energy providers by using an entity as a source for current and future prices. That way any other extension, Node-RED flow, Python script could provide the price data. 

**Describe alternatives you've considered**
Well, the alternative would be to integrate each and every energy provider individually

**Additional context**
Here's a link to the Tibber API reference docs: https://developer.tibber.com/docs/reference#price

**Comment by jonasbkarlsson** [comment]
Thanks for the suggestion. Currently, the integration supports two electricty price provider integrations, Nordpool and Energi Data Service.  This covers many countries in northern Europe. Next planned step is to add support of the Entso-e integration (#64), which should extend the coverage to a large part of Europe.

The support of these price integration is done by connecting to entities in these integrations. If I understand your suggestion, you suggest to add entities in this integration that others from the outside could update with price information, right?

One way to do this would be to add
- Number entiry : current_price
- Text entity: prices_today
- Text entity: prices_tomorrow

where the information for the two Text entities could be on the format [{"start": datetime, "value": float},...]

Note that to provide the input to these entties will not be trivial. There will be some effort needed from those who would like to use this way. So I wonder how many will use this, compared to how many will use existing price integrations?

**Comment by HWiese1980** [comment]
Ah, I see. Thank you very much. I'll try and set it up. I'm seeing a small issue with the EV SOC that I'll need support with. I'll open another issue for this as it is not exactly a feature request or bug report.

**Comment by HWiese1980** [comment]
It works like a charm, by the way. Thank you!
