### ISSUE TITLE
EV SOC not "live", but available after a refresh - however,...

### ISSUE THREAD

**Issue by HWiese1980** [jonasbkarlsson/ev_smart_charging#140]
## Version of the custom_component
Version 1.6.0

## Configuration
Mazda MX-30, Raspberry Pi 4, Home Assistant Supervisor with countless customizations

## Describe the issue
My Mazda provides SOC, however, only after a request from the API of the MyMazda app. The SOC is provided by the API, which requests it from the car over cell network. That update has a couple issues: 

* it takes a while after the request
* it is not exactly reliable all the time
* it is rate limited
* it wakes the car up, which costs charge of the 12V board battery every time (I learned the hard way)

So it should not be requested too many times in a row. 

On the plus side, charging the car is pretty slow anyway (it only charges with a single phase, so max 7.5kW). So I guess it should suffice to update SOC once or max twice an hour or something, or request SOC once and assume a fixed rate of charge and a given max capacity of the battery. I think I can achieve that with a custom sensor built in Node RED or AppDaemon. 

My point is, is `ev_smart_charging` able to handle such a situation?

**Comment by jonasbkarlsson** [comment]
I think it should be ok. The SOC doesn't need to be updated often. Especially if the target SOC is controlled by the car. It would be good to have a reasonable accurate SOC value before charging so that that the initial charging schedule become ok.

**Comment by HWiese1980** [comment]
Okay, I'll just try it out. Well, I did, last night. I'll have to fiddle around with the settings. For some reason it only charged for 1h and then stopped. The charger entered a "Finishing" state that I could not get it out of without rebooting it. No idea what happened there... but that's probably off-topic here.

**Comment by HWiese1980** [comment]
Ah, of course, thank you for your work and support! ;-) Keep rocking!
