### ISSUE TITLE
Keep charger on after completion time

### ISSUE THREAD

**Issue by moorgrove** [jonasbkarlsson/ev_smart_charging#153]
**Is your feature request related to a problem? Please describe.**
When keep charger on is active the charging stop when completion time (06:00) is reached. I have pre heating of cabin activated in the car at a time (06:10) after the completion time and therefore the power from that is drawn from the batteries instead of the charger.   

**Describe the solution you'd like**
When keep charger on is active, the charger should be active until the car gets disconnected. Regardless if the completion time is reached.

**Comment by jonasbkarlsson** [comment]
Which version of the integration are you using?

How often have you seen this? Once, but it usually works? Several times? Every time?

**Comment by moorgrove** [comment]
Im running 1.7.0. Using it with a CTEK that communicates over OCPP. I seen it several times, not sure if it has worked any time.
<img width="1378" alt="Skärmavbild 2023-03-07 kl  09 39 17" src="https://user-images.githubusercontent.com/25015949/223368914-9b64df32-72a6-42b0-a9f9-33a036c6a94e.png">

**Comment by jonasbkarlsson** [comment]
I also use CTEK over OCPP.

Can you add the entites `sensor.ev_smart_charging_charging` (from this integration) and `sensor.xxxxxx_status_connector` (from the OCPP integration) to that history view?

**Comment by moorgrove** [comment]
Maybe I have som settings "outside" ev_smart_charging that affects the charger but it's strange that the time coincides with the completion time of ev_smart_charging. I could test to set the completion time to 05:00 tomorrow and see if it behaves the same.

EV Smart Charging Charging switched to off 06:00:00
OCPP Status Connector switches to Finished 06:00:02

<img width="1385" alt="Skärmavbild 2023-03-07 kl  11 39 07" src="https://user-images.githubusercontent.com/25015949/223399591-6a3f67e4-0f6b-4cf5-b960-0e661b75b642.png">

**Comment by jonasbkarlsson** [comment]
At 05:45, the car seems to be fully charged.
At 05:55, it seems like the pre heating of cabin starts, and the charger provides power to the car.
But then something happens at 06:00...

Can you add `switch.ev_smart_charging_ev_connected` and the entity that you use for `EV SOC entity` as well to the history?

**Comment by moorgrove** [comment]
Have worked last week so the earlier problems must have been some glitch :)
