### ISSUE TITLE
Setup of EV Smart Charging does not accept external entities created by Remote HomeAsistant

### ISSUE THREAD

**Issue by ksvard** [jonasbkarlsson/ev_smart_charging#155]
I have two instances of Home assistant. One for regular, front end stuff and one for backend like solar panels, EV charge, etc.
The entities from the backend system is mirrored into the regular one with the integration Remote_Homeassistant by [lukas-hetzenecker](https://github.com/custom-components/remote_homeassistant/commits?author=lukas-hetzenecker).

When I try to use entities created by this integration, like Charger Control Switch, the entity is not recognized by the config and therefore not possible to finalize. Eg. entity="switch.ha_power_laddbox_mode" --> Error message: "Charger control switch entity not found". 

The switch entity is working with current automation rules.

I would appreciate any information if there is a workaround or fix, as it would complicate the setup to move integrations into one instance of HA instead of using already existing entities

Best regards

**Comment by jonasbkarlsson** [comment]
So you have the EV Smart Charging integration on the main HA, and on the remote HA you have `switch.ha_power_laddbox_mode`, and when configuring EV Smart Charging that switch can not be found, right?

I don't know the details of the Remote HomeAssistant, but have you read [this](https://github.com/custom-components/remote_homeassistant#missing-components)? Not sure if it is relevant or not.

If you in the main HA look in HA->Settings->Devices & Services->Entities, and search for `switch.ha_power_laddbox_mode` there, will you find it? Which Entity ID is shown there?

If the correct Entity ID is shown there, then I'm a bit puzzled.

One possible workaround is to not configure the switch in EV Smart Charging, and to use automations instead to control your switch. See for example [this](https://github.com/jonasbkarlsson/ev_smart_charging#example-of-automation-to-start-charging) and [this](https://github.com/jonasbkarlsson/ev_smart_charging#example-of-automation-to-stop-charging).

**Comment by ksvard** [comment]
I have set up the integration with automations settings the entities on my remote HA. Seems to work OK. I will do a test run and see that it functions as expected. Thanks for the automation templates.

**Comment by jonasbkarlsson** [comment]
I installed Remote Home-Assistant, and I can see that it mirrors the states of the entities, but not the actual entities. And this integration is using the actual entites to verify that the entity IDs provided during configuration are valid. For the switch, it might be ok to only verify the state, but for the price entity it will not be as straightforward.

Since you seems to have found a way to make it work, I will not spend time on trying to fix this.
