### ISSUE TITLE
Add support solar (or green) power, home battery, charging modes, nordpool_diff

### ISSUE THREAD

**Issue by MrOzzOnline** [jonasbkarlsson/ev_smart_charging#165]
I've been using a similar automation to control my charging schedule using entso-e pricing. 
More info see: https://community.home-assistant.io/t/ev-charging-scheduling-solution-with-solar-power-and-a-home-battery/482225

To be fair a in my opinion a few essential things are missing from your integration:
* Green charging support: start charging when free solar power > kwh
* home battery support: control charging based on the home battery level
* Charging modes: a lot of chargers have interesting modes - normal, eco mode, peak saving mode, ...
* norpool_diff: this integrating gives a 'score' of the current price compared to the price for the next few hours. This is VERY handy to determine the best moments to charge your car. See https://github.com/jpulakka/nordpool_diff

I use the following options:
* automatic / manual schedule
* only charge at night (which is 1900 to 0700)
* use nordpool_diff 6 hours (= interval, 6 hours)
* use nordpool_diff 20 hours (= interval, 20 hours)
* charge from home battery only, ignore previous options together with a min battery level option to start and stop (default = 40% min to start and 25% min to stop)
* only start charging when the home battery is full (meaning >98%)
* Ignore all options and start charging when the car is connected

Small note: I have a Polestar 2 which doesn't have a SOC available. To be fair, you don't need it to run efficiëntly.

The result:
![image](https://user-images.githubusercontent.com/115424166/226004355-b3b014ae-9fed-47a7-8a91-0d0206e7a6a7.png)
![image](https://user-images.githubusercontent.com/115424166/226005087-81b9b94f-41f7-435e-bd4d-1f1e0db255dc.png)

**Comment by jonasbkarlsson** [comment]
Thanks for sharing. To support home batteries is already on my to-do list, so that will probably be added. To do even more advanced control is something I need to think about.

**Comment by stejo388** [comment]
Hi,
I also love to have support for soar energy, in my case which don´t have batteries I would like to use the solar energy as long it´s available. That´s is In´m producing more energy that I´m using and then using the lowest price.

A question, could I use manually start and stop the charging to use the solar energy during the day, will it then automatically recalculate the hours it should charge after I stop with the manually charging?

**Comment by woopstar** [comment]
> Hi, I also love to have support for soar energy, in my case which don´t have batteries I would like to use the solar energy as long it´s available. That´s is In´m producing more energy that I´m using and then using the lowest price.
> 
> A question, could I use manually start and stop the charging to use the solar energy during the day, will it then automatically recalculate the hours it should charge after I stop with the manually charging?

Create an automation that triggers when you have excess power from solar energy and force start the charger. You need to create a sensor that measures the excess power you have from solar and counts the power you put into your EV.

Adding solar support etc. is something I think should be seriously reconsidered. Is it really the purpose of this integration? There are so many ways to add solar/battery support automation in HA, that could trigger this integration, which currently has the main focus of "charge your EV when the electricity price is low".

**Comment by jonasbkarlsson** [comment]
> A question, could I use manually start and stop the charging to use the solar energy during the day, will it then automatically recalculate the hours it should charge after I stop with the manually charging?

I would recommend to make an automation that when you want to manually start charging does
- Start charging
- Turn `switch.ev_smart_charging_smart_charging_activated` off

and another automation that when you want to manually stop charging does
- Stop charging
- Turn `switch.ev_smart_charging_smart_charging_activated` on

This will ensure that integration will recalculate the planned charging when you manually stop charging.

**Comment by stejo388** [comment]
> > A question, could I use manually start and stop the charging to use the solar energy during the day, will it then automatically recalculate the hours it should charge after I stop with the manually charging?
> 
> I would recommend to make an automation that when you want to manually start charging does
> 
>     * Start charging
> 
>     * Turn `switch.ev_smart_charging_smart_charging_activated` off
> 
> 
> and another automation that when you want to manually stop charging does
> 
>     * Stop charging
> 
>     * Turn `switch.ev_smart_charging_smart_charging_activated` on
> 
> 
> This will ensure that integration will recalculate the planned charging when you manually stop charging.

Great, I will try that. One more question, could you use start/stop manually charging if you have stopped the automatically charging?

**Comment by jonasbkarlsson** [comment]
> Great, I will try that. One more question, could you use start/stop manually charging if you have stopped the automatically charging?

Yes, you can.
