### ISSUE TITLE
Configuration issue or is readme not updated? Charging control integration 

### ISSUE THREAD

**Issue by AOskam** [jonasbkarlsson/ev_smart_charging#167]
## Version of the custom_component
Version 1.8.0

## Configuration
HAOS on proxmox vm

## Describe the bug

Hi, 

i have a model 3 which i can control with HA via the Hacs Tesla integration. Readme tells me that the car charger should be filled out in the “Charging control integration” field. This field is not available to configure unless it is the same as the charger control switch entity which is in fact available. 

![E68E2217-4931-4306-B0CD-FE0791786CDE](https://user-images.githubusercontent.com/117292242/229139126-d735f012-cb1a-4ac1-aa5f-0f50192ce1a8.jpeg)

**Comment by jonasbkarlsson** [comment]
“Charging control integration” is new configuration parameter for the next release.

Here is the [readme for v1.8.0](https://github.com/jonasbkarlsson/ev_smart_charging/tree/v1.8.0). 

I now noticed that HACS in HA doesn't show the readme for v1.8.0, but the latest checeked-in version. Hmm. I thought it was supposed to show the correct version of the readme.
