### ISSUE TITLE
Integrate minimum soc before continuing charging smart.

### ISSUE THREAD

**Issue by AOskam** [jonasbkarlsson/ev_smart_charging#168]
**Is your feature request related to a problem? Please describe.**

when returning at home i would like to give the car a basic charge as i arrive with very low soc’s regularly. So i would like to charge to e.g. 20% stop charging and then wait for the cheapest hour.

**Describe the solution you'd like**
Create an option to set a minimum charge after which automatic charging kicks in. 

**Describe alternatives you've considered**
I can fix this using automations in Home assistant, I’m aware of this, however I think it would be a nice addition to this integration 

**Additional context**

**Comment by jonasbkarlsson** [comment]
Thanks for the suggestion. That's a good idea.

**Comment by RienduPre** [comment]
+1

**Comment by LasseLegarth** [comment]
+1
I absolutely agree, this would be a really cool feature

**Comment by Arjanmus** [comment]
Is the feature 'Optional setting of minimum SOC level that should be reached indepently of the electrity price' not exactly meant to achieve this?
However, it's functionality is unclear to me, since my car does not start charging immediately when I come home with low battery, while this is set to 30.

Can someone explain? Thanks:)

**Comment by jonasbkarlsson** [comment]
@Arjanmus Optional setting of minimum SOC level will charge during the hours when cost is lowest, even if the cost is above the price limit.

It will not start charinging as soon as you connect the car to the charger. Actually, that is the behaviour asked for in this feature request.

**Comment by Arjanmus** [comment]
Ah ok, that is clear. So if no price limit is set, the minimum SOC option will have no effect.
Thanks! Hopefully this requested feature will be implemented.

**Comment by jonasbkarlsson** [comment]
Part of release [v1.9.0](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.9.0).
Turn on switch `switch.ev_smart_charging_low_soc_charging` and set the desired level of initial charging (default 20%) in `number.ev_smart_charging_low_soc_charging_level`.
