### ISSUE TITLE
Odd time selected for charging.

### ISSUE THREAD

**Issue by AndersHoglund** [jonasbkarlsson/ev_smart_charging#169]
## Version of the custom_component
Version v1.8.0

## Configuration
Running HA in WMware on Ubuntu

## Describe the bug
Charging is selected to start at 22:00 while there is a lower price tomorrow at 12:00.

![Screenshot 2023-04-01 at 18-55-26 Overview – Home Assistant](https://user-images.githubusercontent.com/15121917/229304776-539b681e-bdbc-4245-b911-6ddc15310be7.png)

**Comment by janneho** [comment]
I did wonder same. Happens when charge completion time is set (at 7 am for me). Does what it should do,

**Comment by jonasbkarlsson** [comment]
This is the intended behaviour when the charge completion time is set to a time in the morning. If you don't have a need for the charging to be completed at a certain time, you can set the completion time to "None", and the cheapest hours known to the integration will be used.

**Comment by AndersHoglund** [comment]
Ah, OK. Thnx.
/A
