### ISSUE TITLE
When does charging start?

### ISSUE THREAD

**Issue by Olgmo** [jonasbkarlsson/ev_smart_charging#178]
Version 1.8.0

## Configuration
Easee charger and Skoda EV.
Smart Charging and Price Limit is Activated.
Config is working okay, it start and stops when is requested.
Set price limit to 0.8. Target SOC set to 90%

## Describe the bug
The charging is starting too late..
Even at Zero cost, it start to late to finish before price rises.

First picture show that price is 0.0 and still "Waiting for chargeing to begin" (at 12:55)
Picture before start:
https://photos.app.goo.gl/hs8W2WAa4erRbZXk7

Then It started automatic at 13:00

4 hours later it is still charging and price is now 0,77
Still charging:
https://photos.app.goo.gl/kq7CWKqfMiEBp3QS9

Why does it not start charging when price drops below 0.8 in the start (at 12:00) ?
---
next day, another example:
Target is set to 100%, Still waiting for charging to start. Why does the logic kick in?
https://photos.app.goo.gl/Fcd58NFB8HeZZA9u5

**Comment by Olgmo** [comment]
Yes, it's still an issue for me.
It is not related to Apexcharts as it did not start charging on low price.
I stopped using this and made my own since it did not work.
Maybe I will try again if there is a new release..

tir. 1. aug. 2023 kl. 10:00 skrev Jonas Karlsson ***@***.***>:

**Comment by jonasbkarlsson** [comment]
Ok, thanks for quickl reply. After a period of low activity, I'm now planning to spend some time to fix some of the known issues. 

I will close this issue now, but if you try a later release and still have issue, please re-open the issue (or create a new one).
