### ISSUE TITLE
When I activate the EV Smart Charging  homeassistant immediately consumes 100% CPU

### ISSUE THREAD

**Issue by rrademak** [jonasbkarlsson/ev_smart_charging#179]
When I activate the EV Smart Charging  is immediately consumes 100% CPU

**Comment by jonasbkarlsson** [comment]
I'm quite sure this issue is not related to the integration. Which version of Home Assistant do you use? I think I have seen people with CPU issues with some of the latest HA versions.

**Comment by jonasbkarlsson** [comment]
No additional information provided for a while. I wil close this issue for now. If the problems still occurs with the latest version of HA, please re-open the issue and provide more detailed information.
