### ISSUE TITLE
Nordpool error: The Electricity price sensor does not have the needed attributes.

### ISSUE THREAD

**Issue by rickroetenberg** [jonasbkarlsson/ev_smart_charging#184]
Hi,
I'm trying to install the add-on, but I get an error when selecting the electricty price sensor.

Error: The Electricity price sensor does not have the needed attributes.

Any idea how to resolve?

I'm using the default addon for Nordpool with VAT included in this sensor

**Comment by ketbla** [comment]
How did you solve it?

**Comment by jonasbkarlsson** [comment]
To use the built-in Nordpool integration, you need to use a template sensor, see [this example](https://github.com/jonasbkarlsson/ev_smart_charging/wiki/Nordpool-(Home-Assistant)).
