### ISSUE TITLE
Easee authorization

### ISSUE THREAD

**Issue by johiodo** [jonasbkarlsson/ev_smart_charging#187]
## Version of the custom_component
Version 1.8.0

## Configuration
Home Assistant Core
Entso-e integration
easee integration
EV  Volvo XC40

## Describe the bug
Our easee station is located on private property near the public street. To prevent anyone from charging at our expense, I only authorized two easee users.
After connecting the car, charging is only possible after authorization, but charging starts immediately after that.

"Manually stop charging" stops charging. After that, averything works as expected.

## Expected behaviour
is there a way to prevent charging from starting after connecting the charging cable and authorization?

**Comment by johiodo** [comment]
After reading more issues, I have discovered that issue #161 matches myn. 
To stop loading after connecting the cable, I made this automation:

`alias: EV Smart Charging - EV charging is off Stop charging
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.laadstation_status
    to: charging
condition: []
action:
  - if:
      - condition: state
        entity_id: sensor.ev_smart_charging_charging
        state: "off"
    then:
      - service: easee.set_circuit_dynamic_limit
        data:
          currentP1: 0
          currentP2: 0
          currentP3: 0
          time_to_live: 0
          device_id: 5dc311710804be7c2d7d14bb29264fb3
mode: single`

And after the car shutdown loading ad 90% cappacity, 

`alias: EV Smart Charging - EV completed
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.laadstation_status
    to: completed
condition:
  - condition: state
    entity_id: binary_sensor.laadstation_cable_locked
    state: "off"
action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.ev_smart_charging_ev_connected
mode: single
`
![EV smart charging](https://github.com/jonasbkarlsson/ev_smart_charging/assets/114515106/71486f5a-d05e-4655-a833-556211da4026)

**Comment by jonasbkarlsson** [comment]
Do you have an automation that controls `switch.ev_smart_charging_ev_connected`? Since you have the Eeasee charger, I think that should be possible. And with such an automation, you shouldn't have the issue you describe. Also, I just released v1.9.0. Please update and see if that might change anything.

**Comment by johiodo** [comment]
Yes I have... Everything is working fine now (after update to v1.9.0).
