### ISSUE TITLE
Allow "binary sensor" as "Charger control Switch"

### ISSUE THREAD

**Issue by mwthrane** [jonasbkarlsson/ev_smart_charging#188]
The tesla wall charger integration uses "binary sensor" and not a switch as the charger entity.
Would be awesome if we could add that under the configuration (the last option)

**Comment by jonasbkarlsson** [comment]
Binary sensors as well as any kind of sensor are read-only. It can't be used to control the integration. I looked at the [Tesla Wall Cconnector](https://www.home-assistant.io/integrations/tesla_wall_connector/) implementation, and I couldn't find anything that will make it possible to start charging using that integration. It only seems to have (read-only) sensors.
