### ISSUE TITLE
Do not wait for new prices if they are already negative

### ISSUE THREAD

**Issue by mwthrane** [jonasbkarlsson/ev_smart_charging#189]
I think it would be awesome to have an option
"Do not wait for new prices, if current price is below XX" Which could be in the negatives.

**Comment by jonasbkarlsson** [comment]
Part of release [v1.9.0](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.9.0).
Turn on switch `switch.ev_smart_charging_low_price_charging` and set the desired level of low price in `number.ev_smart_charging_low_price_charging_level`.
