### ISSUE TITLE
I would like to create a branch with update for Readme.md

### ISSUE THREAD

**Issue by svendhoest** [jonasbkarlsson/ev_smart_charging#214]
**Is your feature request related to a problem? Please describe.**
I would like to add an example for integration with Go-E Gemini

**Describe the solution you'd like**
Update the readme.md

**Additional context**
Pushing a branch for review was denied

**Comment by jonasbkarlsson** [comment]
Instead of pushing a branch for review, can you create a pull request instead?

**Comment by svendhoest** [comment]
Ah, i just had to learn to fork and then create a PR from a fork. Thanks!
