### ISSUE TITLE
"No charging planned"

### ISSUE THREAD

**Issue by cgillber** [jonasbkarlsson/ev_smart_charging#216]
Version v1.9.0

Hi! I'm a happy user of this integration but for the last month or so I've started to get issues with charging my car. I never get a charging planned.

- Manually starting/stopping works fine.
- In screenshot both nordpool prices and EV SOC is visible
- Worked well with my previous car, and worked well for 2-3 months on my current before issues started to appear.
- Last week I managed to get planned charge for two days. Not sure how; I just restarted HA and different apps and got is temporarily working somehow... 

<img width="1463" alt="image" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/17291323/e92b5397-3ce2-4ce1-b26a-4af9a4701704">

Occasionally I get the following error below where smart charging fails to fetch vehicle battery level. This is only intermittent though and in the screenshot battery level is valid. 

Also started manually now and I can verify EV SOC gets updated as charging level increases. 

Got any idea what the issue could be?

Log:
----------------------------------------------------------------------- 

This error originated from a custom integration.

Logger: custom_components.ev_smart_charging.coordinator
Source: custom_components/ev_smart_charging/coordinator.py:671 
Integration: EV Smart Charging (documentation, issues) 
First occurred: October 22, 2023 at 1:02:28 PM (19 occurrences) 
Last logged: October 22, 2023 at 1:02:41 PM

SOC sensor not valid: <state sensor.volvo_VIN_battery_charge_level=unavailable; state_class=measurement, unit_of_measurement=%, device_class=battery, icon=mdi:battery-80, friendly_name=C40 Battery Charge Level @ 2023-10-22T13:02:20.348145+02:00>
SOC sensor not valid: <state sensor.volvo_VIN_battery_charge_level =unknown; state_class=measurement, unit_of_measurement=%, device_class=battery, icon=mdi:battery-80, friendly_name=C40 Battery Charge Level @ 2023-10-22T13:02:39.572143+02:00>
SOC sensor not valid: <state sensor.volvo_VIN_battery_charge_level =unknown; state_class=measurement, unit_of_measurement=%, device_class=battery, icon=mdi:car-battery, friendly_name=C40 Battery Charge Level @ 2023-10-22T13:02:39.572143+02:00>

Kind regards,
Chris
```

**Comment by cgillber** [comment]
After some more analysis it seems I get these errors when HA is restarted. The vehicle's battery level is fetched every 300s and thus EV Smart Charging recognises the battery level a few minutes after boot.

A (very) vague hypothesis from my end is that a flaky battery status perhaps triggers some bug in EVSC?

**Comment by jonasbkarlsson** [comment]
Thanks for reporting. Need to check if sudden loss of SOC value could cause this.

Meanwhile, if this happens again. Can you turn off the `switch.ev_smart_charging_smart_charging_activated`, and then turn it on again? Will this create a schedule?

**Comment by cgillber** [comment]
Thanks Jonas for responding. I guess I just found the issue; I usually don’t use price limit but it was enabled and limit was set to 0 SEK. Silly me…

Great app! I’m
