### ISSUE TITLE
EV Smart Charging EV connected keeps turning on binary sensor

### ISSUE THREAD

**Issue by storebatfar** [jonasbkarlsson/ev_smart_charging#220]
## Version of the custom_component
Version 1.9.0

## Configuration
Tesla Custom Integration and EV Smart Charging 1.9.0

## Describe the bug
I have been trying to setup an automation to Turn on/off the EV Smart Charging EV connected switch, when the binary_sensor.tesla_charger changes to state 'No power'.

Here is where it gets wierd. Once the automation runs or I manually set EV Smart Charging EV connected to 'off', a few seconds later the binary_sensor.tesla_charger changes to 'Power connected', even though no cable is connected to the car.

**Comment by jonasbkarlsson** [comment]
That sounds really wierd. How could anything you do in Home Assistant affect `binary_sensor.tesla_charger`?

How does your automation look like? Can you paste the yaml code?

**Comment by storebatfar** [comment]
@jonasbkarlsson I am able to reproduce it by just turning off the EV Smart Charging EV connected.
I have re-installed the EV Smart Charging integration and completed the setup with new intities.

If I switch off 'switch.test_ev_smart_charging_ev_connected' I wait a few seconds and the entity 'binary_sensor.milky_charger' turns on (Power Connected).

**Comment by storebatfar** [comment]
I think I have found the issue and it looks like it might be something in the Tesla Custom Integration.
If the car is not connected to power and I quickly turn 'switch.tesla_charger' on and off, this will then change 'binary_sensor.tesla_charger' to on (Power Connected).

My guess is that when 'switch.test_ev_smart_charging_ev_connected' is switched off, it triggers something with 'switch.tesla_charger', which then changes 'binary_sensor.tesla_charger' to on (Power Connected).
