### ISSUE TITLE
Cannot selevt SMART EV devices

### ISSUE THREAD

**Issue by molcam** [jonasbkarlsson/ev_smart_charging#221]
Version 1.9.0 - GARO charger

I am experiencing an odd problem. I am trying to build a simple automation with a button by my charger where I can manually start or stop the SMART EV with a button. I am only experiencing this issue with SMART EV (I have not reinstalled SMART EV yet...).

When I make an automation and select action in the automation generator I have 2 EV SMART in my device list (not sure why). I select the one where I can select actions, and I can select an action, but when I then press the edit YAML or try to SAVE the automation, the action dissapears (see figure). I only have this issue with SMART EV. Will try to reinstall it and see what happends....

![Skärmbild 2023-11-03 154857](https://github.com/jonasbkarlsson/ev_smart_charging/assets/77750942/8b8a5948-b416-4967-8e8f-4d307ab5d50c)

**Comment by jonasbkarlsson** [comment]
Hi! Yes, that sounds odd. I have only one EV SMART device in my device list, and when I select an action and save the automation, the action remains as one would expect it to do.

**Comment by molcam** [comment]
Hi!
I agree - it was an odd issue - I first tried to redownload the plugin - it had no effect but after removing it and then reinstalling it, it  now work as expected. Issue resolved!

**Comment by jonasbkarlsson** [comment]
There is already a push button that can be used to manually start charging. Isn't that enough?

**Comment by molcam** [comment]
The idea was to not having to use the phone to set the charging correct - just a simple button. I am sure that I can figure it out by modifying the charger instead of Smart EV.
