### ISSUE TITLE
Recalculate schedule on change of "EV target SOC" - not an issue at all as it calculates when the car is connected ....

### ISSUE THREAD

**Issue by AMajland** [jonasbkarlsson/ev_smart_charging#223]
I'm new to this - just added it yesterday so sorry if I’ve just not understood it properly and its a support issue and note a feature request :-)

We have gotten used to having a look at the electricity prices including a forecast for the following days. I.e. significantly longer than the prices are known. In HA I have EnergyDataService with Carnot forecast . But we are following https://www.facebook.com/elforbrug But basically if there is a lot of wind in the weather forecast the chance of good prices are good :-)

Our usage varies a lot. Some days 40% is more than adequate while we need 100% on others. So, we are used to having to set the target SOC manually depending on the need and the price forecast (So far that has been easier to just set the Target SOC than trying to automate it. The one that has the longest takes the EV while the other takes the ICE. So not easy to automate ......) 

Opportunistic charging does not solve the issue of easily telling how much is needed, but looks like a good solution if you i.e. need xx% a day but would like to charge to yy% when the prices tomorrow are good.

I Assume that the charging schedule will be recalculated when the car is connected or when new prices are available. 

**But it would be nice with the visual feedback of a changed schedule as soon as you have changes the EV target SOC**

The planned charge on top of the prices in a apexchart is very easy for all to understand and verify with a quick glance.

PS even though my car has a SOC available tough Skoda Connect their servers are not 100% reliable - So I expect that I will have to my own logic in-between that monitors it and report a "safe low SOC" when it has not updated for a prolonged time.

**Comment by AMajland** [comment]
I think the non-issue i saw yesteday was just that the schedule was not calculated before the next days prices are known.

Now the car is home early today but not connected

![image](https://github.com/jonasbkarlsson/ev_smart_charging/assets/97510471/c823cb1d-9de6-412d-815d-891269c73435)

And the schedule is updated when i change the target SOC.

 
![image](https://github.com/jonasbkarlsson/ev_smart_charging/assets/97510471/4ff089b8-f2ec-4d54-b6e3-27ff26c10cbb)

**Comment by jonasbkarlsson** [comment]
Seems like there is no issue anymore, so I will close this.
