### ISSUE TITLE
EVBox Elvi - EV SOC entity not found.

### ISSUE THREAD

**Issue by johnegilhope** [jonasbkarlsson/ev_smart_charging#227]
I've installed EV Smart Charge ver. v1.9.0. an OCPP ver. v0.5.0
My EV charger is EVBox Elvi and my car is Hyundai Ioniq 2019.
I cannot read sensor.charger_soc from EV charger and I connot read sensor.my_ev from my car.

How can I go around "EV SOC entity" and start using EV Smart Charge?

**Comment by jonasbkarlsson** [comment]
Have you set up the OCPP integration to work with your EVBox Elvi?
[https://home-assistant-ocpp.readthedocs.io/en/latest/installation.html#configure-your-charger](https://home-assistant-ocpp.readthedocs.io/en/latest/installation.html#configure-your-charger)

And then to get a sensor for the EV SOC you need an integration that can get information from your car. I think this it what you need. Have you installed this one?
[https://github.com/Hyundai-Kia-Connect/kia_uvo](https://github.com/Hyundai-Kia-Connect/kia_uvo)

**Comment by johnegilhope** [comment]
I have set up both Evbox and OCPP, no worries there. I can start, stop and read available parameters from Evbox.
My car is Hyundai Ioniq 2019, and has not integrated any kind of communication to any app, so I can't get any SOC information from the car. The Evbox/OCPP parameter "sensor.charger_soc" says "unknown". That means I also don't get any SOC data when I follow the tips under the COPP app install notes.

So back to my question, how is it possible to bypass the "EV SOC entry" parameter in the OCPP setup?

**Comment by jonasbkarlsson** [comment]
Yes, you can create a Number Helper in Setting -> Devices & Services -> Helpers (for example named "SOC" that typically will create an entity `input_number.soc`), and then use this entity when configuring the integration. 

For the integration to work well, the value of the SOC should change between charging cycles. One way to do this is to set the SOC value to 100 when charging is completed, and then set it to an appropriate value when starting next charging cycle.

**Comment by johnegilhope** [comment]
So your saying, that as long as I have added the helper, SOC,wich gives:"input_number.soc". Then I should be able to set up the "EV Smart Charging" integration?

**Comment by jonasbkarlsson** [comment]
You can use the helper entity as the EV SOC entity when configuring the integration. You can choose any name. "soc" was an example.

**Comment by johnegilhope** [comment]
I don't know why I misunderstood the installation procedure/descition and thougt the field should be entered by a number.
But when I added "input_number.soc" in the field, I got past the installation screen.
