### ISSUE TITLE
GUI option to change the value of config variable charging percent per hour

### ISSUE THREAD

**Issue by KentHage** [jonasbkarlsson/ev_smart_charging#228]
I would like to have an opportunity to change the value of the config variable "charging percent per hour". As far as i can see in the code, it is hard coded to 6, if it is undefined. This variable is used to calculate how many hours the car needs to charge from current SOC to the target SOC. Unfortunately this default value it is too big and I would like to set it to 4 or 5 instead so I would get more hours to charge.

**Comment by jonasbkarlsson** [comment]
Hi! You can change it in the GUI. Settings->Devices & Services->Integrations->EV Smart Charging, and then click on `1 device`. Then you can change the charging speed in the Configuration tile.

**Comment by KentHage** [comment]
Thank you! The title "Charging speed" was a little confusing and I thought it was the amount of amps the charger was giving the car.
