### ISSUE TITLE
Keep charger on option starts charging when desired SOC is increased

### ISSUE THREAD

**Issue by storebatfar** [jonasbkarlsson/ev_smart_charging#237]
## Version of the custom_component

Version v1.10.0

## Configuration
I have an Easee charger and my car is a Tesla Model 3. I have an automation set for making sure my EV is connected.
SOC is set by the car and charging is controlled by the Easee charger. Charging completion time is set to 7:00 AM.

## Describe the bug
First of all, thank you for a great integration. Absolutely love it!
My issue is regarding the 'Keep charger on' feature.

In my case I have my cars SOC at 81% and the desired SOC is set to 80%.
I have 'Keep charger on' disabled.

If I then turn on 'Keep charger on' and then change the desired SOC to eg. 85%, the charing is started and not waiting for the best time / cheapest prices.

If I instead keep the feaure 'Keep charger on' turned off and then change the desired SOC to eg. 85%, the integration finds the best time / cheapest prices and plans the charging.

## Debug log

```text

Add your logs here.

```

**Comment by jonasbkarlsson** [comment]
Thanks for the report. I will look into this.

**Comment by jonasbkarlsson** [comment]
Should be fixed in [v2.0.0](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v2.0.0).
