### ISSUE TITLE
Additional states for sensor.ev_smart_charging_status

### ISSUE THREAD

**Issue by Mattzon** [jonasbkarlsson/ev_smart_charging#238]
Hi,
Thank you for this great integration :) I have a feature request that would make it easier for me to create automations.

**Is your feature request related to a problem? Please describe.**
I'm trying to use confirmable notifications to set/change the "low SOC charging" level if it is necessary to reach a higher SOC level even though the electricity price is above the set limit. In order to send this confirmable notification when charger is plugged in and electricity price is high I need a sensor state that states if "low soc charging" will be applied.

**Describe the solution you'd like**
Would it be possible to add  a new state to sensor.ev_smart_charging_status (Waiting for low SOC charging to begin). This would enable me to set a condition for the notification.

Best regards,
Mathias

**Comment by jonasbkarlsson** [comment]
Hi, I'm not sure I understand what you would like to do. There is no `Waiting for low SOC charging to begin`. Low SOC charging happens if `switch_active`, `switch_ev_connected` and  `switch_low_soc_charging` are active and if `ev_soc < low_soc_charging`. There is no dependency on the electricty price.

**Comment by Mattzon** [comment]
I'm trying to achieve a condition that is true when `low_SOC_charging` will be applied for the next charge and use it to send an actionable notification.
But I realize now that I can use the `ev_soc<low_SOC-charging` as the condition instead.

Thank you for your fast reply

//Mathias
