### ISSUE TITLE
Accept input_boolean as a switch

### ISSUE THREAD

**Issue by Dominic-070** [jonasbkarlsson/ev_smart_charging#239]
For the 'Charger control switch' please accept 'input_boolean' as a 'switch'. My charger doesn't have a chaging switch, so I created an input_boolean that switches the charger between 0A and 16A. 

<img width="525" alt="image" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/62623885/60a59eb8-d40b-4b29-a8b0-a64302a94254">

**Comment by jonasbkarlsson** [comment]
Hi! Actually, the integration itself is a sensor with boolean values "on" and "off". So in your case, leave the "Charger control switch" item in the configuration empty (or a single space to remove an old value). And then use the automations suggested  [start-charging](https://github.com/jonasbkarlsson/ev_smart_charging?tab=readme-ov-file#example-of-automation-to-start-charging) and [stop-charging](https://github.com/jonasbkarlsson/ev_smart_charging?tab=readme-ov-file#example-of-automation-to-stop-charging). You don't need to create your own input_boolean.

**Comment by Dominic-070** [comment]
Thnx!
