### ISSUE TITLE
waiting for charging to begin (updates?)

### ISSUE THREAD

**Issue by Symbiot78** [jonasbkarlsson/ev_smart_charging#240]
more of a question.

I started the charge via the charger integration because i couldn't understand how the EV smart charging integration was going to ( I lost time & patience :) )
anyway... EV Smart charging keeps saying "waiting for charging to begin) even though the charging has already started and has been running for 5-10-15 minutes. 
Is it not checking anything? like the charger switch configured in EV smart charging config?

**Comment by jonasbkarlsson** [comment]
The EV Smart charging does not check if you have started charging using another method.
