### ISSUE TITLE
The integration does not plan charging, when car is disconnected?

### ISSUE THREAD

**Issue by kenni** [jonasbkarlsson/ev_smart_charging#244]
This is likely more a support question than an issue with the integration. I've setup the integration (or at least I thought so), but I can't seem to get the integration to plan a charge. I must be missing something obvious.

I'm using the Energi Data Service integration, which get updated with new electricity prices ~13:00-13:45 every day. I've setup an automation to update the "EV connected" switch when the car gets connected to the charger. The integration is setup to control the charger.

Today at 08:00 (Charge completion time), the "EV Smart Charging Status" changed to "Waiting for new prices". All good.

At 10:14 I disconnected the car and took it for a ride. "EV Smart Charging Status" changed to "Disconnected".

At ~13:30 Energi Data Service was updated with new prices for the following day.

At 14:25 I got back home and connected the car to the charger. "EV Smart Charging Status" changed to "No charging planned", even though the current SOC is less than the target SOC. I would have expected it to change into something like "Charging planned" and that it would charge the battery tonight.

What am I missing? I suppose this is a very common use case, with people driving to work in their car during daytime, and hence have the car disconnected when the new electricity prices arrives.

<img width="325" alt="Screenshot 2024-01-14 at 14 52 25" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/486971/69cb1371-aafa-46ad-b25c-46a7c5583dc3">

<img width="327" alt="Screenshot 2024-01-14 at 15 22 03" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/486971/69d2a158-acd1-4fbd-b6bc-d82b38d82770">

<img width="327" alt="Screenshot 2024-01-14 at 15 22 18" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/486971/448512d6-7980-4091-a8b6-5b4b170a4cc2">

<img width="554" alt="Screenshot 2024-01-14 at 15 27 18" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/486971/318a1a5c-d35d-4a72-9b18-161fdaa4ceae">

**Comment by kenni** [comment]
"Apply price limit" was the cause of the issue, I do not know how that got activated, but once it was deactivated, the integration immediately scheduled the charge. Yay! :)

**Comment by jonasbkarlsson** [comment]
I was just about to point that out, but you closed the item before I was readly with my comment... :-)

**Comment by Inrego** [comment]
> I was just about to point that out, but you closed the item before I was ready with my comment... :-)

I just had the same issue. After using this integration for a while, I suppose I accidentally enabled price limit.
May I suggest adding another attribute that provides a reason when no charging is planned?

**Comment by Inrego** [comment]
Or possibly more simply add a notification in HA when enabling price limit if the price limit is 0. As to remind people to supply a price limit if that feature is enabled.
Or a third option could be to ignore price limit enabled if the price limit is 0 - however this could cause confusion for people who actually want a price limit of 0 (not likely?), but proper documentation of this could help prevent confusion.

**Comment by jonasbkarlsson** [comment]
Notifications added in [v2.5.0](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v2.5.0).
