### ISSUE TITLE
Support andreas-berg fork of entso-e integration

### ISSUE THREAD

**Issue by acejoh** [jonasbkarlsson/ev_smart_charging#250]
Hi,

Thank you for your work on this integration!
I'm using a fork of the entso-e integration (https://github.com/andreas-berg/hass-entsoe-dayahead) which is better maintained than the original one. However the electricity price structure does not match the format of the original integration. When I attempt to add the data to the ev_smart_charging device it I get the following error:
![image](https://github.com/jonasbkarlsson/ev_smart_charging/assets/18048545/256e1140-5b42-4704-bc0a-1e734043ce11)

Would it be possible to add support for this integration?

Kind regards

**Comment by andreas-berg** [comment]
Hi guys, @acejoh got me interested in the ev_smart_charging and the possibility to integrate the hass-entsoe-dayahead (a fork of JaccoRs original but seemingly unmaintained) component.
This component currently only provides two sensors: todays prices (in the configured timezone) and tomorrows prices (same TZ, empty array when tomorrow not available).  
In both cases, the sensor value is in the simplest way possible, arrays of floats. 
The European electricity markets will change (of course not all at the same time, where would be the fun in that ;)) to a 15-min slot and this will not break this array but it will break any client logic that expects the data in 1h slots. 
@jonasbkarlsson If you have a clear preference on new stable interface, pls let me know and I'd be happy to implement this in the hass-entsoe-dayahead.

**Comment by jonasbkarlsson** [comment]
Support of template sensors in [v1.11.0](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.11.0).

If you make a template sensor that will work with fork https://github.com/andreas-berg/hass-entsoe-dayahead, please post it here.

Or if @andreas-berg would like to implement this [price information format](https://github.com/jonasbkarlsson/ev_smart_charging/wiki/Price-sensor) in that fork.
