### ISSUE TITLE
`ev_smart_charging` calls `async_add_job`, which is deprecated (HA 2024.4 and up)

### ISSUE THREAD

**Issue by hmmbob** [jonasbkarlsson/ev_smart_charging#252]
## Version of the custom_component
Version 1.10.0

## Describe the bug
HA 2024.4.0b5 reports the below log message. 

## Debug log
> 2024-04-02 16:32:17.996 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'ev_smart_charging' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/ev_smart_charging/__init__.py, line 52: hass.async_add_job(

**Comment by jonasbkarlsson** [comment]
Thanks for reporting. Fixed in #257. Will be part of next release.
