### ISSUE TITLE
Height of black bar

### ISSUE THREAD

**Issue by RogMoe** [jonasbkarlsson/ev_smart_charging#258]
I just installed EVSC and I like it! Adjusted little details to suit my country settings and all okay now.
There's however one thing I don't understand.
**What does the height of the black bar indicate?** In my case it show "0,24" (no units whatsoever)

Maybe I'm missing something here, but wouldn't it be more pleasing to the eye to have the  black bar follow the price-graph?
I'm not that good with Apexcharts to accomplish this myself...

Thx for your reply.

![SEVC_1](https://github.com/jonasbkarlsson/ev_smart_charging/assets/74535064/a2731756-8501-4a2b-8628-38d465944148)
![SEVC_2](https://github.com/jonasbkarlsson/ev_smart_charging/assets/74535064/f67d98f8-93d1-4f28-b02c-717e9e272541)

Just in case; here's my code.

`type: custom:apexcharts-card
now:
  show: true
  label: Now
  color: blue
locale: en
header:
  show: true
  title: Smart Charging
  show_states: true
graph_span: 2d
yaxis:
  - min: ~0
    decimals: 2
    apex_config:
      forceNiceScale: true
span:
  start: day
apex_config:
  legend:
    show: false
  xaxis:
    labels:
      show: true
      format: HH
      rotate: 0
      decimals: 2
      rotateAlways: true
      hideOverlappingLabels: true
      style:
        fontSize: 10
        fontWeight: 10
series:
  - entity: sensor.ev_smart_charging_charging
    name: Electricty price
    unit: €/kWh
    data_generator: >
      return entity.attributes.raw_two_days.map((entry) => { return [new
      Date(entry.start), entry.value]; });
    type: line
    float_precision: 2
    show:
      in_header: before_now
    extend_to: false
    color_threshold:
      - value: 0
        color: blue
      - value: 0.17
        color: green
      - value: 0.25
        color: orange
      - value: 0.35
        color: red
      - value: 0.45
        color: magenta
      - value: 0.5
        color: black
  - entity: sensor.ev_smart_charging_charging
    name: Charging
    data_generator: >
      return entity.attributes.charging_schedule.map((entry) => { return [new
      Date(entry.start), entry.value]; });
    type: area
    curve: stepline
    color: black
    float_precision: 2
    show:
      in_header: false
    extend_to: false
experimental:
  color_threshold: true
`

**Comment by jonasbkarlsson** [comment]
The height of the bar has no meaning. It is set to 75% of the highest price to easily be able to generate the Apexchart in this particular way. When the lowest price is close to zero, it would be difficult to see the charging schedule with your suggestion. So therefore the current Apexchart is given as an example in the documentation.

**Comment by RogMoe** [comment]
Okay, this makes sense!
