### ISSUE TITLE
Set timer chaging finish

### ISSUE THREAD

**Issue by perjmolsen** [jonasbkarlsson/ev_smart_charging#287]
Feature request: Can you please make an input field, so it is possible to set a finish charge time also, ex if I plug in my car and I need to to be fully charged next morning at 07.00

Thanks, and love your work 👍😃

**Comment by jonasbkarlsson** [comment]
Hi! There is a configuration entity called `select.ev_smart_charging_charge_completion_time` that let you set a finish charging time.
