### ISSUE TITLE
Smart charging ignores disconnected EV

### ISSUE THREAD

**Issue by mortenmathiasen** [jonasbkarlsson/ev_smart_charging#293]
## Version of the custom_component

Version 1.11.0

## Configuration
I use HA apps EV smart charging and Volkswagen Connect together. An automation is setup to pass connectivity status from VW to Smart charging. The value switch.ev_smart_charging_ev_connected is then maintained automatically. 

## Describe the bug
If cable is not connected I would expect EV smart charging status to become 'Disconnected'. What happens instead is that EV smart charging schedules charging point of time and status becomes 'Waiting for charging to begin'. This is quite confusing to the user that expects that charging will begin but that can't happen as the charging cable is disconnected.

## Debug log

```text

Add your logs here.

```

**Comment by jonasbkarlsson** [comment]
Can you please provide some details.

**Comment by mortenmathiasen** [comment]
> Can you please provide some details.

Sure. Details are added. Let me know if additional information is needed.

**Comment by jonasbkarlsson** [comment]
Should be fixed in [v2.0.0](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v2.0.0).
