### ISSUE TITLE
Add a switch or other mechanism to not interrupt HPC-charging

### ISSUE THREAD

**Issue by maeklund86** [jonasbkarlsson/ev_smart_charging#298]
**Is your feature request related to a problem? Please describe.**
I accidentally forgot to switch off the smart charging, and connected to a HPC-charger (100kW). The automation then of course programmed the cheapest hours as expected and stopped the charging.

**Describe the solution you'd like**
It would be nice to have an option to not interrupt charging sessions once the power exceeds X kW (typically 11 kW). Alternatively a way to smart charge only at certain locations like home etc.

**Describe alternatives you've considered**
The alternative is to remember to turn off the smart charging when headed to a HPC.

**Comment by corvy** [comment]
Just write a simple automation to enable smart charging then the car is at home, and disable when the car is away.

**Comment by jonasbkarlsson** [comment]
The intented way to handle this is to write an automation that controls the `switch.ev_smart_charging_ev_connected`. This will prevent the integration to interfer with HPC-charging.

**Comment by maeklund86** [comment]
I ended up doing just that. In my case the car integration provides a sensor for charging speed. I created an automation that switches off the `switch.ev_smart_charging_ev_connected` if the power is over 11kW.
This is probably something that most people will want to add, maybe an addition to the documentation would suffice.

**Comment by corvy** [comment]
You should rather automate when `switch.ev_smart_charging_ev_connected` gets turned on. In my case I can use the switch sensor from Easee to turn it on (when car is connected to easee charger, turn the ev_connected swith on). You could do the same, or use device tracker as an alternative. Or if you can get the information from the car that it is connected to a charger (when car is home and charger is connected, turn on ev_connected, else turn off ev_connected). 

The 11 kW option is at best a workaround, for me that would not work as I can charge 22kW at home.

**Comment by maeklund86** [comment]
Hmm, you might be right. I don't want the smart charging to be active when charging at a public charger, (which can be an 11 kW charger) but I do want the smart charging active at my parents' house as well as my home. My car integration reports when a charger is connected and power provided. Need to think further

**Comment by corvy** [comment]
Just add a zone at your parents home, and set the automation to enable ev_connected if the car is connected and is home OR zone_parents.

**Comment by maeklund86** [comment]
@corvy This was good advice, never found a use for zones before. I added a condition to the automation that the position can not be "Away". That way adding new zones will automatically be included for the smart charging. Thanks a bunch!
