### ISSUE TITLE
Automatic enable charging based on EV location and disabling while fast charging

### ISSUE THREAD

**Issue by Perimec** [jonasbkarlsson/ev_smart_charging#299]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be useful to have an automatic smart charging activation when the EV is within a specific location (for ex. home). In addition, smart charging should be automatically disable while fast charging.

**Describe alternatives you've considered**
Script could be in place but this would become not so user friendly

**Additional context**

**Comment by corvy** [comment]
Why dont you write an automation to enable smart charging when your cars device_tracker is at home? I only enable smart charging when my car is at home, and connected to the charger. Depending on your charger and car you should be able to quite easily write an automation for this.

**Comment by jonasbkarlsson** [comment]
Similar reqest as #298. See suggestions given to that request.
