### ISSUE TITLE
price_in_cents required?

### ISSUE THREAD

**Issue by magnushasselquist** [jonasbkarlsson/ev_smart_charging#36]
Version 1.0.3

In the Nordpool integration I am having:
price_in_cents: false (and that is the standard value)

It seems that this integration requires the price to be in cents from Nordpool?
In the APEX chart I see my price from Nordpool treated as "öre"=cents, hence guessing that this integration is requiring the price from Nordpool to be in cents?

Apex chart:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/5380854/199918700-8b2f75ef-2e08-4288-9447-3d075ebfade7.png">

Current Nordpool prices:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/5380854/199918816-c1d8560a-f889-4176-9509-ec96d43128ce.png">

**Comment by jonasbkarlsson** [comment]
The integration itself doesn't care about the currency or if the price is expressed in cents or not. The "öre/kWh" that you see in the Apex chart comes from the configuration of the Apex chart. Just change the line `unit: ' öre/kWh'` to `unit: ' SEK/kWh'`.

**Comment by magnushasselquist** [comment]
Thanks! Fixed on my end.
