### ISSUE TITLE
Sensor for summery of schedule

### ISSUE THREAD

**Issue by Strixx76** [jonasbkarlsson/ev_smart_charging#38]
**Is your feature request related to a problem? Please describe.**
Not with how the integration works, but with my small main fuses... :joy:

**Describe the solution you'd like**
A sensor with the summery of next charge period. Can't decide what the state should be, but I lean towards a binary sensor that is on if there is a upcoming loading session scheduled and off if not. So it would be off after the last session and until a new is scheduled after next days prices is received, unless the price limit causes that there is no upcoming session.

And then as extra state attributes I would like to get next start and stop time (datetime), and the length i hours of the period.

**Describe alternatives you've considered**
One could course achieve the above with a super complicated template sensors, but why should one?

**Additional context**
Why do I need this then?

I need to be able to plan (automate) the heating of my spa (which is also connected to Home Assistant off course). Because when I heat it, the automatic load limit (external, not connected to Home Assistant) of my Wallbox will reduce the power which means the calculations of time needed to charge the car will be wrong, and the wanted level will not be reached.

The second reason is I want an easy fast way of displaying if the car will be charged on a wall mounted tablet. The alternative to see the calculated period now is as the example with an apex chart. But my home view has no room for more charts... :satisfied:

**Comment by jonasbkarlsson** [comment]
Thanks for the suggestion. 

As an alternative to a new sensor, would just additional extra state attributes to the existing sensor be good enough? For example,
- Charging is planned : 'true' or 'false'
- Planned start time : datetime or TBD
- Planned stop time : datetime or TBD
- Planned number of hours : int

Or would a binary sensor make things better?

What should the start and stop times be if there is not planned charging? 'unknown', 'null', 'false'?

The "Planned number of hours" would be the number of planned hours, which could be less than the time difference between the stop and start times, since the price limit might temporarily stop the charging.

**Comment by Strixx76** [comment]
Sure, it would work as good as an extra sensor. A binary sensor does not make things better. It is easy to use attributes in automation in both HA and Node-RED, and for displaying info it does not matter to what kind of sensor the attributes belongs.
The reason I suggested an new sensor is that I read somewhere that it is not recommended to have attributes change when the sensor it self does not, because of database size. But I realize now that this is already the case so, it will not add to the database.

As for what the type of start and stop attributes should be when there is no scheduled charging I would have to say that `unknown `or `unavailable` would be best. I don't know which is the correct one. But it think `None` would also work to be displayed in the UI without extra templateing, but I am not sure, and I can't test it my self in the next week or two.

And finally, yes, the planned number of hours should take in consideration the hours not charging due to price limit.

**Comment by jonasbkarlsson** [comment]
I have made a [beta version v1.1.0.dev1](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.1.0.dev1) with additional attributes. Can you install this and check if this is what you asked for? Use [the method described here to install](https://hacs.xyz/docs/faq/select_version/). I used `None `in the code for the start and stop time when there is no planned charging.

**Comment by jonasbkarlsson** [comment]
I have noticed that the "Charging is planned" does not change to "false" after charging is finished, so I will fix that. However, my main wish for feedback is if the contents and the format of the new attributes are ok or not.

**Comment by jonasbkarlsson** [comment]
Thanks for testing and the feedback. I will fix the current bug and do proper testing of the code before releasing it.

**Comment by jonasbkarlsson** [comment]
Hopefully the [v1.1.0.dev2](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.1.0.dev2) release has fixed the bug. Will do some additional testing before releasing.
