### ISSUE TITLE
Request: Allow max_price to be set from a sensor

### ISSUE THREAD

**Issue by cnrd** [jonasbkarlsson/ev_smart_charging#50]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to dynamically set the max price, however the price of power seems to fluctuate quite a bit in periods.

I would love to be able to set the max_price with a sensor, such that I can for example define the max_price as the 25th percentile of the last 30 days, such that charging will only happen if the power is cheap compared to the last 30 days.

**Describe the solution you'd like**
Allow defining the max_price using a sensor.

**Comment by jonasbkarlsson** [comment]
First version of dynamic configuration parameteres now available as pre-release [v.1.5.0-dev2](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.5.0-dev2)

**Comment by jonasbkarlsson** [comment]
Dynamically setting of configuration parameters using service calls supported as part of release [v1.5.0](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.5.0).
