### ISSUE TITLE
Possibility to include last hour next day

### ISSUE THREAD

**Issue by Strixx76** [jonasbkarlsson/ev_smart_charging#63]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The possibility to include 23:00-24:00 the next day in the calculations.

**Describe alternatives you've considered**

**Additional context**
Now that there is a possibility to choose none continuous charging it would be great if the calculations could be done on all known hours. Today one can only choose until 23:00 the next day. This night this is the result then because of that:
![After_23](https://user-images.githubusercontent.com/17635047/208316242-6199af17-652d-41e4-8955-468fe72d04b0.png)

If all hours where considered there wouldn't been any charging scheduled between 20:00 and 21:00. Instead that hour would have been scheduled between 23:00 and 24:00 the next night.

**Comment by jonasbkarlsson** [comment]
Is that really needed? 

Actually, I'm thinkig of (temporarily) restricting the `Charge completion time` to be 13:00 as the latest. The integration does not work as intended now. A new schedule is calculated after the next days prices comes after 13.00. So in your example there is no guarantee that hour 23:00-24:00 will be used for charging, if the prices the following day will be even lower. So before considering your suggestion, I think the integration needs to be changed to handle `Charge completion time` later than 13:00 in a better way.

Is `Charge completion time` later than 13:00 important? I think it could be, but it would be good to hear others' view.

**Comment by Strixx76** [comment]
Yes! Completion time after 13:00 is very important for me. The way your integration works now is the reason I use it instead of "powersaver" in Node-RED. I want to postpone the charging if there is cheaper prices coming up, because I only need to charge my car about 5 hours a week (we don't drive that much).

I can see the problem it causes when you really need to charge according to the schedule. But I would suggest a different approach than restring to 13:00 hours. 
Is it possible that adding a switch that enables or disables rescheduling the charging before the present schedule has ended would solve this problem?

**Comment by jonasbkarlsson** [comment]
I would prefer to fix the code so that the rescheduling is delayed until after the `Charge completion time` has passed. To ensure that charging is completed by that time. I think that will achieve what you originally asked for. 

In addition, I can mention that I have plans to add a `Super saver` switch, that if the price for the last hour tomorrow is really low, then less will be charged this night. With the hope that the price will in general be lower next night.

**Comment by Strixx76** [comment]
"Super saver" switch would be a really great feature! Maybe you could not only compare the last hour but also the, lets say the last 3 hours and also "trend". IE if the mean of 21:00 to 24:00 for the next night compared with this night and the "trend" for the last 3-5 hours next night is lower prices than we cancel all scheduled charging and wait for next price update. Because there is a risk that it is only the hour 23-24 that is cheap.

Then about the rescheduling after completion time. I have noticed that changing `SOC` or `Minimum EV SOC` after a charging period makes the integration recalculate the schedule, which is bad in my use-case. I tried to make an automation that updates the SOC for my car with the amount charged. But then if I didn't reached the `Minimum EV SOC` due to carious reasons, there was a new schedule calculated which started the charging again but at a higher price. This is I guess the preferred way for a lot of users, but not for me. I would rather have skipped the last hour of charging and waited for new prices to arrive.
So I would suggest that this recalculation is not done when using "super saver mode".

I have thought a lot how to improve the calculations or how to implement user limitation to improve the savings in my own use-case. That is when there is almost never any need for completing the schedule or need for charging this day or even the next day. Right now I am think that maybe a dynamic price limit would do the trick.
Then with the help of a template sensor I could set the limit to X% of the mean of all known prices, but never more than Y.

This together with the Super saver mode would make the integration out standing!!! (Maybe this should be a separate feature request?)

BTW. Merry Christmas 🎅

**Comment by jonasbkarlsson** [comment]
Have spent some time thinking about when it make sense to reschedule, and have now chaged the rules so that rescheduling also happens if the current time is before the charge completion time of the day. This makes the rescheduling more aggressive than before, so if the planned charging wasn't enough to reach the target SOC, the integration will now schedule more charging.

This is probably not at all what you are asking for. Instead, I think what you would like to do is to not have a charge completion time at all. So I have added a "None" as possible value for the charge completion time, and if that is selected, then the integration will keep updating the schedule with all the price information that is available.

I made a pre-release with this, [v.1.5.0-dev1](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.5.0-dev1)

**Comment by Strixx76** [comment]
As you wrote I think this almost opposite of what I want to achieve.

I can't quit figure out what "None" actually will result in, I think I will have to try it out to see.

But if I understand it correctly you are now compelled to have a true SOC that is updating during the charging to not get continuous charging after it has started?

IE in my use case where I have two "dump" cars. They cant report SOC, so I need to set it manually in the UI in when I come home and connect the car. So I set `SOC` to 40%, the `EV target SOC` to 100% and `Minimum EV SOC` is set to 60%.
If I don't update SOC manually (with an automation of course) this will mean that it will charge even if the price is higher than `Electricity price limit`, because it will never reach `Minimum EV SOC`.

Or am I missing something here? I will hopfully later to day have chance to do some testing.

**Comment by jonasbkarlsson** [comment]
You're probably right. I think the changes in v1.5.0-dev1 leads to a need to have a true SOC. That's not inline with my overall intention with the integration.

One way to handle it is to add a new switch that tells the integration that the SOC sensor is the true SOC or not.

Or if I can figure out a different logic to handle late charge completion time (which was the reason behind the changes in v1.5.0-dev1).

**Comment by jonasbkarlsson** [comment]
One way to handle this would be to not reschedule after a charging period if the SOC value hasn't increased. And in that case do rescheduling at `Charge completion time` or when tomorrow's prices becomes available if None has been selected as `Charge completion time`.

One potential problem would be if the user (or an automation) updates the SOC value during charging, which would make the integration reschedule after the current charging is finished. There is no rescheduling done now while charging.

**Comment by jonasbkarlsson** [comment]
Did a pre-release [v1.5.0-dev3](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.5.0-dev3) with the solution I described above. It's a bit ugly, but hopefully it will work in a good way in most cases. The main problem is as I mentioned above, if the SOC values is changed during charging in a way that does not represent the actual SOC at the end of the charging. If you need to change the SOC value, please make sure charging is not ongoing.

Note that rescheduling needs to be done once per 24h. Now the `Charge completion time` is used to decide when that happens. And with None meaning when the new prices information is available.

**Comment by Strixx76** [comment]
So if I understand you correct there will not be any rescheduling at all if I set `Charge completion time` to None, except from when the new prices arrives? If so, that is not a good solution, because the prices arrives at about 13:00. If the user arrives home at the evening the scheduled charge will be calculated for the `SOC` that was entered (or received) before the new prices arrived, and there will be no adaptation to the actual `SOC`.

I am trying to come up with an smart solution but there are so many factors, and if you change one rule it might affect others negatively.

But... What if, when choosing None as `Charge completion time` you will lock rescheduling when the first charge period starts, and then unlock rescheduling again when new prices arrives? I think that will solve the problems, but there are for sure something I have missed...

B.T.W. Happy new year. 🍾 🎆

**Comment by jonasbkarlsson** [comment]
Changing the `SOC` will also trigger a reschedule (if tomorrow's prices are available or if the current time is before the charge completion time), unless charging is ongoing.

If you don't have access to the actual `SOC` dynamically, then I would suggestio to do the following:

Alternative 1:
- Manually set `SOC` to 100% when the charging is complete.
- Manually set `SOC` to your current `SOC` when you want to schedule charging (typically after connecting the EV to the charger)

Or if you have information from the charger that the EV is connected/disconnected.
Alternative 2:
- Make an automation that set `SOC` to 100% when the EV is disconnected
- Manually set `SOC` to your current `SOC` when you want to schedule charging (typically after connecting the EV to the charger)

Happy new year!

**Comment by jonasbkarlsson** [comment]
Supported as part of release [v1.5.0](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.5.0).
