### ISSUE TITLE
Add Entso-e integration support

### ISSUE THREAD

**Issue by jonasbkarlsson** [jonasbkarlsson/ev_smart_charging#64]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Adding support of the Entso-e integration as an additional way to get the electricity prices.

**Additional context**
The [Entso-e integration](https://github.com/JaccoR/hass-entso-e) and a [community topic](https://community.home-assistant.io/t/custom-component-entso-e-day-ahead-energy-prices/467127).

**Comment by ronaldt80** [comment]
That would be great! Great project you made. I tried to program something with automations in HA but optimization is still quite cumbersome using automations.

**Comment by Dominic-070** [comment]
That would be really great!

**Comment by jonasbkarlsson** [comment]
I have now added support for the Entso-e integration in [v1.8.0-dev3](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.8.0-dev3).

However, is the Entso-e integration working? Seems to behave strangely for me.

**Comment by ronaldt80** [comment]
Which ento-e integration do you use? The latest version also doesn't do what it should do for me. So reverted back to 0.2.0 which does what it should do for me

**Comment by jonasbkarlsson** [comment]
I had version 0.3.0. Changed to version 0.2.0 now. Got the correct prices. Seems better.

**Comment by ronaldt80** [comment]
Yeah, don't know what happened there; need to raise an issue/ PR but had other priorities and 0.2 has been working for a couple of months now without issues

**Comment by jonasbkarlsson** [comment]
Part of [v1.8.0](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.8.0).
