### ISSUE TITLE
Config entry title set by user

### ISSUE THREAD

**Issue by Strixx76** [jonasbkarlsson/ev_smart_charging#68]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Ability to change or set the config entry title in the config flow.

**Describe alternatives you've considered**
None.

**Additional context**
I have two instances of the integration. One for each of my two cars. I can change the name after installation but that only (optionally) affects the naming of the senors. It would be great if we could set the title of the config entry, so that it is displayed in the integration page in Home Assistant so that one could easily see which instance is which.

**Comment by jonasbkarlsson** [comment]
Can you give an example of an integration that let you set title of the config entry during initial installation? So that I can look at the code...

**Comment by Strixx76** [comment]
If I was at home at my office I could have made an pull request, but I am not. But here is how I would have done it:

In `async def _show_config_form_user` in `config_flow.py` add a required field in `user_schema` for "Name" and the key of your choice, lets say CONF_NAME. You could use your `DeviceNameCreator` class for the default name.

Then change line 119 (in the main branch) to:
`return self.async_create_entry(title=self.user_input[CONF_NAME], data=self.user_input)`

I am pretty sure you also should change line 166 to:
`return self.async_create_entry(title="", data=user_input)`

I would also of course change the code so that you use this new name and not the old user_input[CONF_DEVICE_NAME] for the default naming of entities.

When I look closer I seems as the whole `async def _show_config_form_charger` is unnecessary since you are setting them in the options flow. And the integration uses the value from the options I think because I have change the price limit from the options flow in my Home Assistant and the schedule changed. If you skip that you need to move the config entry creation to  `async def _show_config_form_user` and you could also remove `async def async_step_charger`.

**Comment by jonasbkarlsson** [comment]
Have now included this in [v1.8.0-dev1](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.8.0-dev1).

I also added the possibilty to change the configuration (name and intput entities). For some reason, if the name is changed, the new name, which is set by `title`, does not take effect.
`return self.async_create_entry(title=user_input[CONF_DEVICE_NAME], data=user_input)`

So now I made a somewhat ugly fix and update the title in `__init__.async_setup_entry()`
`entry.title = get_parameter(entry, CONF_DEVICE_NAME)`
This does update the name of the integration, but unfortunately it doesn't trigger the browser to update what is shown on the screen.

Is there a way to trigger a refresh?

**Comment by jonasbkarlsson** [comment]
Fixed the refresh of the browser when the name of the integration is changed, see [v1.8.0-dev2](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.8.0-dev2).

And I have checked the code in Core, the title is not sent with `hass.config_entries.async_update_entry()` by the `OptionsFlowManager`.

**Comment by jonasbkarlsson** [comment]
Thanks for the comments. I will look into it.

**Comment by jonasbkarlsson** [comment]
Have now removed the use of the dictionary key CONF_DEVICE_NAME outside `config_flow.py`.

And then I made it so that if the Integration name is changed by the user, the Device name will automatically be changed. And if the Device name is changed by the user, the Integration name will automatically be changed. Changes of the Entity names are handled by Home Assistant.

This is now in [v1.8.0-dev3](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.8.0-dev3).

**Comment by jonasbkarlsson** [comment]
Part of [v1.8.0](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.8.0).
