### ISSUE TITLE
Allow "EV SOC entity" to be optional

### ISSUE THREAD

**Issue by Aephir** [jonasbkarlsson/ev_smart_charging#69]
**Is your feature request related to a problem? Please describe.**
I have an older PHEV, and there is no state of charge reporting. I know it typically needs ~3 hour to charge with my openEVSE at 16A, and I use a custom script that calculates the cheapest 3 hour interval ending before 7 am (8 am in weekends, holidays and when on "vacation_mode").

I'd like to try out this integration, as mine is just a hacky AppDaemon script, but since it requires a SOC sensor to set up, I can't.

**Describe the solution you'd like**
Make SOC sensor optional, replace by stating the kWh needed to charge each night, or just a charging interval to use in place of an SOC sensor.

**Describe alternatives you've considered**
I am currently using an alternative (home made script), as I didn't know this integration existed until at few days ago (following a mention in an Issue for the Nordpool sensor).

**Comment by jonasbkarlsson** [comment]
It is possible to use the integration without having a car with a SOC sensor. In the section **Integrating with EVs** in the documentation, the following is suggested.

> A lot the functionality in this integration relies on knowing the EV SOC. However, if this information is not available, then it is still possible to use this integration to control a charger with very basic functionality. In this case, create a Number Helper in Setting -> Devices & Services -> Helpers (for example named "SOC" that typically will create an entity `input_number.soc`), and then use this entity when configuring the integration.
> 
> For example, if the SOC entity is set 60, the Target SOC entity is set to 100 (or not configured) and the `Charging speed` parameter is set to 10, then there will be 4 hours of charging each night, (100-60)/10 = 4.

**Comment by Aephir** [comment]
OK, thanks!
