### ISSUE TITLE
Question: Configuration 

### ISSUE THREAD

**Issue by mustachedkdev** [jonasbkarlsson/ev_smart_charging#71]
Hi

I have some questions about this integration.

I have setup the NordPool integration with the following configuration

![Skærmbillede 2022-12-25 kl  10 57 59](https://user-images.githubusercontent.com/25482923/209463684-afeb113b-2a07-48e3-bdc8-232a89289d5c.png)

And Ev Smart Charging with the following configuration

![Skærmbillede 2022-12-25 kl  10 58 40](https://user-images.githubusercontent.com/25482923/209463702-8cb6d599-2ac9-4034-bb85-ce43b531fa0a.png)

However it seems like that the integration never plans for the charging even though the price is below the limit.

![Skærmbillede 2022-12-25 kl  11 00 05](https://user-images.githubusercontent.com/25482923/209463745-59359983-1bb2-4ceb-a380-2704d1244190.png)

Have I done something wrong in the setup?

**Comment by jonasbkarlsson** [comment]
A new charging plan is made after the prices for tomorrow are available, typically shortly after 13:00. So please wait a little.

**Comment by sadiq81** [comment]
That did the trick. Thank you.
