### ISSUE TITLE
Charge value change from 100 to less triggers re-evaluation of periods

### ISSUE THREAD

**Issue by oveand** [jonasbkarlsson/ev_smart_charging#99]
Version 1.5.1

## Configuration
Easee charger and input_number describing SoC.

## Describe the bug
This morning I noticed that charger has continued to re-start charging after this has stopped. I have an input_number describing the SoC which is updated when my car reports an updated SoC value. Charging was planned to stop at 05:00 and when charging stops I manually update the input_number.ev_smart_charging_soc to 100, as I understand is recommended.
15 minutes later my car reports a SoC of 98 and it seems like EV Smart Charging re-evaluates charging schedules then and then starts charging until 06:00 where the charging stops, sets SoC to 100, and then 06:03 charging starts again. The car is only charging very slow during the latest percentages.

Would it be possible to have a setting telling EV Smart Charging to not re-evaluate charging all the time (like before the change)? Or is there another workaround?

![billede](https://user-images.githubusercontent.com/13885942/212388807-354a656f-4bf1-446b-bbab-d9139958b253.png)

Unfortunately I don't have any debug logs.

**Comment by jonasbkarlsson** [comment]
First, if you your input_number.ev_smart_charging_soc is automatically updated from your car, then you should not set it manually to 100 when the charging stops. That recommendation was only for those that don't have automatic updates of the SOC value.

Now looking at  your graph, it seems like you have target_soc = 100, and there was a scheduled charging until 05:00. And at that time the car was charged to 98%. It also seems like you have set charge completion time to 07:00 or later.

So with the latest update the integration will at 05:00 continue to charge, since the target has not been reached and there is still time left to the charge complete time.

Given the above, are you saying that you would have prefered the charging to stop at 05:00, even though the target soc was not reached? Can you elaborate a bit about this?

**Comment by oveand** [comment]
Thank for for the quick responsen, I will pour you a cup of coffee, it's well deserved.

I understand your confusion and I will explain my rationale.

I have a Nissan Leaf integrated with HA but updates can be delayed up to one, i.e, HA does not necessarily know the true SoC of the car. Therefore an input_number is updated upon Leaf SoC change.

Second, charging speed is in general 9%/hour but for the last 3-4% the internal charger is slowing down and only charges very slowly.

Due to thus, the old 1.4.x version did work quite well for me as charging was planned and vehicle was usually charged to 97-100% during the cheapest charging periods, then charging was stopped and this was fine. The 1.5.x branch reschedule charging into more expensive periods and the pre-optimized plan is not sticked too.

I see that this could partly be overcome by reducing target SoC to 95% but the delayed SoC update can potentially still cause the scheduler to be confused, right?

I could of cause just prevent the input_number being updated from Leaf SoC during charging hours and then set this to 100 when charging stops. But this would most likely only work with one continuous period of charging, right?

**Comment by oveand** [comment]
Quite non-linear charging profile (kWh) for the last approx 5%
![billede](https://user-images.githubusercontent.com/13885942/212420508-a09e0623-c37b-4776-bf77-5aa406f26431.png)

**Comment by jonasbkarlsson** [comment]
Thanks for the coffee! Much appreciated.

The easiest way for you to reduce the additional charging after the initially planned charinging period would be to lower the target SoC. Maybe you don't need to lower it to 95% as you suggested, but maybe 97-98% would be enough to drastically reduce the additional charinging time.

You didn't write how long the SoC updates are delayed. You only wrote "one". Did you mean one minute or one hour? If it's one minute, then the delay shouldn't be a problem. If it's one hour, then setting the target SoC to 95% or so could be a way to handle such a long delay.

There are probably ways to achieve exactly what you want with some clever designed automations. But the motivation I had to write this integration was to be able to have rather advanced charging strategies without the need to write a lot of complicated automations.

I think the new 1.5.x strategy with rescheduling if the target soc was not reached make sense for many. The average charging price will of course go up if additional charging is added after the planned charinging, but the alternative would have been to start earlier, but that will also increase the average charging price. So I think there is a fundamental choice between the importance to reach the target SoC and the important to reduce the charging cost. 

I was hoping that the extra chariging cost to reach the target SoC would be small, but if it is seen as a problem, then I think the best solution is for me to add switch that selects one of these two strategies.

**Comment by oveand** [comment]
Sorry, the missing unit was in a very unfortunate place, but the default SoC update interval is 1 hour, though it can be lowered when charging, but recommended it not too low as this can drain the 12 V battery. 15 minutes should though not make a problem.

I like your philosophy of making an as advanced charging module as simple as possible, I fully support this! And too many buttons/settings definitely increases complexity. I think I will optimize my setup testing different target SoCs and update intervals and see how this works out. Therefore I recommend you to not implement any further settings but I thank you very much for your feedback and this discussion.
